# Site settings
title: Fullstack Notes
header-img: img/home-bg.png
email: billfero@gmail.com
copyright_name: theBoyMo
description: > # this means to ignore newlines until "baseurl:"
  Journey of a Fullstack Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  theBoyMo
learn_profile: theBoyMo
email_username: billfero@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
